codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
    patch:
      default:
        target: 80%
        threshold: 0%
    changes: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
