codecov:
  require_ci_to_pass: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - dev
    - main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_not_found: success
        informational: false
        only_pulls: false
        branches:
          - dev
          - main
