codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        base: auto
        if_not_found: success
        informational: false
        only_pulls: false
    patch:
      target: 80%
      threshold: 0%
      base: auto
      if_not_found: success
      informational: false
      only_pulls: false
    changes: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - dev
    - main
