[build]
  command = "yarn build-storybook"
  publish = "storybook-static"

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (NEXT_PUBLIC_)"